const ColorsList = {
	authBackground: "#F7F7FC",
	borderColor: "#F0F0F0",
	modalBackground: "#FAFAFA",
	black: "#000",
	blackTransparent: "rgba(0,0,0,.5)",
	borderBg: "#cdd3e0",
	danger: "#f04184",
	pink: "#e831ae",
	dangerSoft: "#fbdbe7",
	gradientPrimary: "#6d1d6d",
	greyAuthHard: "#dedede",
	greyBg: "#f9faf7",
	greyFont: "#959595",
	greyFontHard: "#5d5d5d",
	greySoft: "#8b8b8b",
	info: "#288cf7",
	infoBg: "#d9e7f4",
	light: "#e0dada",
	primary: "#cd0192",
	primaryColor: "#cd0192",
	primarySoft: "#f233ac",
	purple: "#904bb7",
	purpleSoft: "#ebcbfd",
	secondary: "#808080",
	success: "#55c09b",
	successHighlight: "#03DAC6",
	successSoft: "#d6f6eb",
	text: "#8b8b8b",
	transparent: "transparent",
	warning: "#f28c71",
	white: "#ffffff",
	whiteColor: "#ffffff",
	whitePlaceholder: "rgba(255,255,255,.5)",
	informationBg: "#BEDCEF",
	informationFont: "#255B7E",
	settingBg: "#FFF1B7",
	settingFont: "#B79936",
	cashbackBg: "#C1EFAD",
	cashbackFont: "#3F8D1D",
}

const infoColorSetting = ["settingBg", "settingFont"]
const infoColorInfo = ["informationBg", "informationFont"]

export { ColorsList, infoColorInfo, infoColorSetting }
